export const memoriesTable = {
    name: 'memories',
    columns: {
        id: 'TEXT PRIMARY KEY',
        project_id: 'TEXT NOT NULL',
        user_id: 'TEXT NOT NULL',
        memory_type: 'TEXT NOT NULL',
        scope_type: 'TEXT NOT NULL',
        scope_key: 'TEXT',
        title: 'TEXT NOT NULL',
        content: 'TEXT NOT NULL',
        summary: 'TEXT',
        status: "TEXT NOT NULL DEFAULT 'active'",
        confidence: 'REAL NOT NULL DEFAULT 0.5',
        strength: 'REAL NOT NULL DEFAULT 0.5',
        decay_score: 'REAL NOT NULL DEFAULT 0',
        importance_score: 'REAL NOT NULL DEFAULT 0.5',
        access_count: 'INTEGER NOT NULL DEFAULT 0',
        success_count: 'INTEGER NOT NULL DEFAULT 0',
        failure_count: 'INTEGER NOT NULL DEFAULT 0',
        last_accessed_at: 'TEXT',
        last_verified_at: 'TEXT',
        last_reinforced_at: 'TEXT',
        expires_at: 'TEXT',
        source_strategy: "TEXT NOT NULL DEFAULT 'auto_extract'",
        explanation_json: 'TEXT',
        metadata_json: 'TEXT',
        created_at: 'TEXT NOT NULL',
        updated_at: 'TEXT NOT NULL',
    },
};
